[project]
name = "ConformalLLM"
version = "0.1.0"
description = "Add a short description here"
authors = ["kKatherine Rosenfeld <krosenf@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
jupyter = ">=1.0.0,<1.1"
transformers = "==4.38.1"
datasets = "==2.17.1"
openai = ">=1.35.1,<1.36"
accelerate = ">=0.31.0,<0.32"
